#
#Sun Aug 09 17:21:42 BRT 2026
app.update_link=https\://drive.google.com/drive/folders/1ZPcNBHANJ7t1pFzYkGYhYgBsjtZhsR8S
caminho.commictagger=
gemini_key_selecionada=Key 1
gemini_model=gemini-2.5-flash-lite
mal.registros_consulta=12
ocr.engine=openrouter
ocr.ollama.model=moondream
ocr.ollama.url=http\://localhost\:11434
ocr.openrouter.model=google/gemma-4-26b-a4b-it\:free
ocr.paddle.cls=true
ocr.paddle.limit_side_len=2880
ocr.paddle.use_angle_cls=true
