#
#Fri May 08 22:15:48 BRT 2026
app.update_link=https\://drive.google.com/drive/folders/1ZPcNBHANJ7t1pFzYkGYhYgBsjtZhsR8S
caminho.commictagger=
gemini_model=gemini-2.5-flash-lite
mal.registros_consulta=12
